"""empty message

Revision ID: 67874db537de
Revises: a054317791da
Create Date: 2022-12-05 17:03:45.393749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67874db537de'
down_revision = 'a054317791da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('votes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('real_estate_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['real_estate_id'], ['real_estates.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'real_estate_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('votes')
    # ### end Alembic commands ###
